# .github/workflows/firebase-hosting-deploy.yml
name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies and build
        run: npm ci && npm run build
      
      - name: List build output
        run: ls -la dist/portfolio-kristoferandersen/browser
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_KRISTOFERANDERSEN }}
          channelId: live
          projectId: portfolio-kristoferandersen
